import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="
      bg-gradient-to-r
      from-green-400
      to-blue-500
      h-full
      w-full
      font-sans
      text-gray-900
      antialiased
      flex
      flex-col
      justify-center
      items-center
      p-4
      ">{children}</body>
    </html>
  );
}
